In [2]:
import numpy as np
n = np.array([1,23,3,4])
print(type(n))

<class 'numpy.ndarray'>


In [5]:
#performance

import time
size = 10000
py_list = list(range(size))
start = time.time()
list_square= [i**2 for i in py_list]
end = time.time()
print(end-start)

n = np.array(py_list)
start1= time.time()
n_2 = n**2
end1= time.time()
print(end1 - start1)



0.002130746841430664
0.0008282661437988281


In [7]:
import sys
print("list :", sys.getsizeof(py_list) * len(py_list))
print("numpy array :", n.nbytes)

list : 800560000
numpy array : 80000


In [8]:
n1 = np.array([1,2,3,4])

In [9]:
n1

array([1, 2, 3, 4])

In [11]:
n2 = np.array([1,"str"])
print(type(n2))

<class 'numpy.ndarray'>


In [14]:
n3 = np.array([[2,3,4],[3,5,6]])
print(n3)
n3.shape

[[2 3 4]
 [3 5 6]]


(2, 3)

In [16]:
n1 = np.zeros((2,3))
n1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
n2 = np.ones((2,3))
n2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
n3 = np.full((2,3), 5)
n3

array([[5, 5, 5],
       [5, 5, 5]])

In [21]:
n4 = np.eye(3)
n4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
n5 =  np.arange(2,5)
n5

array([2, 3, 4])

In [25]:
n5 =  np.linspace(10,20,3)

In [26]:
n5

array([10., 15., 20.])

In [30]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

print(arr.shape)
print(arr.dtype)
print(arr.nbytes)
print(arr.itemsize)
print(arr.ndim)


(4, 3)
int64
96
8
2


In [34]:
n4 = np.array([1,2,3,4], dtype='float64')
n4.dtype

dtype('float64')

In [37]:
n5 = n4.astype('int64')
n5.dtype
n5

array([1, 2, 3, 4])

In [39]:
n1 = np.array([[3,4,5],[4,6,7]])
n1.shape

(2, 3)

In [40]:
n1.reshape((3,2))

array([[3, 4],
       [5, 4],
       [6, 7]])

In [42]:
n1.flatten()

array([3, 4, 5, 4, 6, 7])

In [43]:
arr = np.array([1, 2, 3, 4, 5])  
print(arr[0])  
# Indexing for 2D array  
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]) # 2D array 
print(arr[0][1]) # 2  
print(arr[1][2]) # 6

1
2
6


In [45]:
arr = np.array([1, 2, 3, 4, 5]) 
idx=[2,3]
print(arr[idx])#fancy indexing

[3 4]


In [46]:
print(arr[arr > 2])  

[3 4 5]


In [47]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])  
print(arr[2:6])  # [3, 4, 5, 6]  
print(arr[:6])  # [1, 2, 3, 4, 5, 6]  
print(arr[3:])  # [4, 5, 6, 7]  
print(arr[::2])  # [1, 3, 5, 7]

[3 4 5 6]
[1 2 3 4 5 6]
[4 5 6 7]
[1 3 5 7]


In [3]:
#1d array
import numpy as np
arr1 = np.array([1,23,3])
arr1.ndim

1

In [5]:
#2d array
arr2 =  np.array([[1,2,3],[2,3,4]])
print(arr2)
arr2.ndim

[[1 2 3]
 [2 3 4]]


2

In [6]:
#3 dim array
arr3 = np.array([[[1,2,3],[3,4,5]]])
print(arr3)
arr3.ndim

[[[1 2 3]
  [3 4 5]]]


3

In [8]:
print(sum(arr1))

27


In [11]:
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 

In [14]:
arr2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
print(np.sum(arr2D))

45


In [17]:
sum_of_columns = np.sum(arr2D, axis = 0) 
sum_of_columns

array([12, 15, 18])

In [18]:
sum_of_rows = np.sum(arr2D, axis = 1) 
sum_of_rows

array([ 6, 15, 24])

In [23]:
arr2D[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [24]:
arr3D = np.array([[[1, 2],[3, 4],[5, 6]], [[7, 8],[9, 10],[11, 12]]]) 

In [25]:
print(arr3D, arr3D.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)


In [30]:
arr3D[0:2, 0:2, 0:1]

array([[[1],
        [3]],

       [[7],
        [9]]])

In [33]:
arr3D[0:2]= 89
arr3D

array([[[89, 89],
        [89, 89],
        [89, 89]],

       [[89, 89],
        [89, 89],
        [89, 89]]])

In [2]:
#Common Data Types
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1.0, 2.0, 3.0])
arr3 = np.array(["hello", "world", "prime", "ai/ml"])

print(arr.dtype)
print(arr2.dtype)
print(arr3.dtype)

print(arr.nbytes)        # 5 elements * 8 bytes each => 40

new_arr = arr.astype("float64")
print(new_arr, new_arr.dtype)

new_arr = np.array([1, 2, 3, 4, 5], dtype="float64")
print(new_arr, new_arr.dtype)


# Complex Numbers
arr1 = np.array([2 + 3j])
arr2 = np.array([5 + 8j])
print(arr1, arr1.dtype)
print(arr1 + arr2)
print(arr2 - arr1)

# Objects
arr = np.array(["hello", {1, 2, 3}, 3.14])
print(arr, arr.dtype)

int64
float64
<U5
40
[1. 2. 3. 4. 5.] float64
[1. 2. 3. 4. 5.] float64
[2.+3.j] complex128
[7.+11.j]
[3.+5.j]
['hello' {1, 2, 3} 3.14] object


In [3]:
# Vectorization & Broadcasting

#Vectorization
arr = np.array([1, 2, 3, 4, 5])

sq_arr = arr ** 2       #square of all nums
print(sq_arr)

arr2 = np.array([6, 7, 8, 9, 10])
print(arr + arr2)      #sum of 2 arrays

#Broadcasting
arr_mul10 = arr * 10    #multiply by 10 to all nums
print(arr_mul10)

arr1D = np.array([1, 2, 3])
arr2D = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1D + arr2D)

[ 1  4  9 16 25]
[ 7  9 11 13 15]
[10 20 30 40 50]
[[2 4 6]
 [5 7 9]]


In [4]:
# Vector Normalization
arr = np.array([[1, 2], [3, 4]])
mean = np.mean(arr)
std_dev = np.std(arr)

print((arr - mean) / std_dev)

#column wise
arr = np.array([[1, 2], [3, 4], [5, 6]])
mean = np.mean(arr, axis = 0)
std_dev = np.std(arr, axis = 0)
print((arr-mean) / std_dev)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]
